### PR TITLE
using the content-length of the response when the header exists

### PR DESCRIPTION
**Pull request by CedricCouton**
Hi,

When exists a header with Content-Length, it is now used to copy stream data to response.

Best regards.

### CODE REVIEW

**Comment by jayjamesjay** [comment]
I really appreciate your work but I do not think that this approach is the best, because you are using Vec to temporarily store a response instead of transferring it directly to a writer, which means that potentially massive amount of data may be allocated in RAM memory (ex. user is downloading a 16GB file).

**Comment by CedricCouton** [comment]
It's true. An option in the request can solve the problem?

**Comment by jayjamesjay** [comment]
No, I don't think so. IMO it's better to drop this idea, because it doesn't provide any performance improvement.

**Comment by CedricCouton** [comment]
What is IMO?

**Comment by jayjamesjay** [comment]
IMO - in my opinion

**Comment by CedricCouton** [comment]
Ok. Io::copy doesn't copy all data in memory?

**Comment by jayjamesjay** [comment]
Please take a look at docs [std::io::copy](https://doc.rust-lang.org/std/io/fn.copy.html):

> This function will continuously read data from reader and then write it into writer in a streaming fashion until reader returns EOF.

It means that it does not have to, e.x.:
- if `writer` is `Vec`, all data will be in memory
- if `writer` is `File`, small portion of data will be stored in RAM memory, then saved to disc, removed from RAM, next portion of data will be stored in RAM memory, then saved to disc, removed from RAM, and so on...

**Comment by CedricCouton** [comment]
Thanks for your explanation. My case is that the server don't send a end message in stream so the copy freeze, the only solution is to use the content length to know when the request is ended. Have you a solution to give me?

**Comment by jayjamesjay** [comment]
Could you point to a website which experiences this issue? So that I could test it on my own.

**Comment by CedricCouton** [comment]
I will start to retry with the request header connection: close.

**Pull request closed without merging**
