### PR TITLE
Add timeouts for Request

### PR DESCRIPTION
**Pull request by ghost**
These functions were added to `Request`:

```rust
pub fn set_connect_timeout(&mut self, timeout: Option<Duration>) -> &mut Self;
pub fn set_read_timeout(&mut self, timeout: Option<Duration>) -> &mut Self;
pub fn set_write_timeout(&mut self, timeout: Option<Duration>) -> &mut Self;
```

Breaking changes are:

- In last version, none of them were used.
- In this pull request, default value for all of them is 1 minute.

That will affect current code.

@jayjamesjay Please review and let me know your opinion. Thank you,

### CODE REVIEW

**Comment by jayjamesjay** [comment]
I apologize for such a long response time but I've been very busy.
I think your implementation is good. But I also have some suggestions:

1. Add test for each of the new functions
2. Remove unnessecary lifetime specifier from `connect_timeout`
3. Directly apply `to_socket_addrs()` method to `(host, port)` instead of using `format!`
4. Replace `match` true/false with `if` `else` statement
5. Move `use std::net::ToSocketAddrs` to the top of the file (just cosmetic change)

Do you agree with my suggestions?

**Comment by ghost** [comment]
@jayjamesjay 

Thank you, I agree with you. I missed the `(&'a str, u16)` implementation of `ToSocketAddrs` from documentation   :-(

Please don't worry about time. I understand.

I'm not sure if committing new changes would make them available in this pull request. So I'm closing this one, and will open new one later.

**Comment by jayjamesjay** [comment]
You don't have to close it. If you commit to the branch, which pull request refers to (in this case `hkcorac:master`), commits will be automatically added to the pull request.

**Comment by ghost** [comment]
@jayjamesjay 

Thank you,

I've finished most of those, except tests for write timeout.

Currently `Request` doesn't expose internal `TcpStream`, or a method to set body. So I'm using these to simulate large request:

- Start a fake loopback server `TcpListener`, which reads 1 byte at a time, and sleeps for 1 second.
- Set a lot of headers to request.

I've tried up to 2 GB of headers. But it has never timed out, in all my tests.

Then I searched around, there are some tools which can help simulate slow network. But all of the tools I found require root access -- which I think is not a good solution.

May I suggest that, since we're forwarding write timeout to `TcpStream`, could we assume that it has been tested? And then temporarily ignore tests for this function?

**Comment by jayjamesjay** [comment]
That's great. I really appreciate your job. I didn't mean to add tests checking internal functionality of `TcpStream` but unit tests in order to make sure that everything is set to expected values, like:
```rust
#[test]
fn request_read_timeout() {
    let uri = URI.parse().unwrap();
    let  mut req = Request::new(&uri);
    req.set_read_timeout(Some(Duration::from_nanos(100)));

    assert_eq!(req.read_timeout, Some(Duration::from_nanos(100)));
}
```

**Comment by ghost** [comment]
@jayjamesjay 

Thanks, now I understand. However I kept functionality tests for connect timeout and read timeout, since they're easy to write.

I've updated some other functions' documentation. Please review new commit and let me know if it's ok.

**Comment by jayjamesjay** [comment]
It's fine. I am going to release it. Please let me know if you have any suggestions.

**Comment by ghost** [comment]
@jayjamesjay Thanks, I don't have suggestions for now.

Thanks again for your library  :-)

**Pull request merged**
